import type { StoreData } from "./types";

export const defaultStore: StoreData = {
  orderSeq: 100,
  settings: {
    name: "Burger House",
    slogan: "Hambúrguer artesanal feito na hora",
    phone: "(21) 97347-0393",
    whatsapp: "5521973470393",
    address: "Rua Exemplo, 100 - Centro",
    city: "Rio de Janeiro - RJ",
    minOrderDelivery: 15,
    deliveryFee: 5,
    deliveryTimeMin: 45,
    pickupTimeMin: 25,
    loyaltyPointsPerReais: 10,
    loyaltyRedeemMin: 10,
    pixKey: "sua-chave-pix@email.com",
    pixMerchantName: "Burger House",
    pixCity: "RIO DE JANEIRO",
    adminPassword: "admin123",
    primaryColor: "#f97316",
    bannerEmoji: "🍔",
    hours: [
      { day: 0, label: "Domingo", open: "18:00", close: "23:00" },
      { day: 1, label: "Segunda-feira", open: "18:00", close: "23:00" },
      { day: 2, label: "Terça-feira", open: "18:00", close: "23:00" },
      { day: 3, label: "Quarta-feira", open: "18:00", close: "23:00" },
      { day: 4, label: "Quinta-feira", open: "18:00", close: "23:30" },
      { day: 5, label: "Sexta-feira", open: "18:00", close: "00:30" },
      { day: 6, label: "Sábado", open: "18:00", close: "00:30" },
    ],
  },
  categories: [
    { id: "cat-burgers", name: "Hambúrgueres", order: 1, active: true },
    { id: "cat-combos", name: "Combos", order: 2, active: true },
    { id: "cat-sides", name: "Acompanhamentos", order: 3, active: true },
    { id: "cat-drinks", name: "Bebidas", order: 4, active: true },
    { id: "cat-desserts", name: "Sobremesas", order: 5, active: true },
  ],
  products: [
    {
      id: "p1",
      categoryId: "cat-burgers",
      name: "Big Mac",
      description:
        "Dois hambúrgueres, alface, queijo, molho especial, cebola e picles no pão com gergelim",
      price: 29.9,
      active: true,
      featured: true,
      highlight: "mais_pedidos",
      extras: [
        { id: "e1", name: "Bacon", price: 4 },
        { id: "e2", name: "Queijo extra", price: 3 },
      ],
    },
    {
      id: "p2",
      categoryId: "cat-burgers",
      name: "Quarterão com Queijo",
      description:
        "Hambúrguer 100% carne bovina, queijo, cebola, picles, ketchup e mostarda",
      price: 28.9,
      active: true,
      featured: true,
      highlight: "mais_pedidos",
      extras: [
        { id: "e1", name: "Bacon", price: 4 },
        { id: "e3", name: "Cheddar extra", price: 3.5 },
      ],
    },
    {
      id: "p3",
      categoryId: "cat-burgers",
      name: "McChicken",
      description: "Frango empanado crocante, alface e maionese no pão com gergelim",
      price: 24.9,
      active: true,
      featured: true,
      highlight: "mais_pedidos",
    },
    {
      id: "p4",
      categoryId: "cat-burgers",
      name: "Cheddar McMelt",
      description: "Hambúrguer, molho cremoso de cheddar e cebola ao molho shoyu",
      price: 27.9,
      active: true,
      featured: true,
      highlight: "promocao",
    },
    {
      id: "p5",
      categoryId: "cat-burgers",
      name: "Duplo Quarterão",
      description: "Dois hambúrgueres, queijo, cebola, picles, ketchup e mostarda",
      price: 34.9,
      active: true,
    },
    {
      id: "p6",
      categoryId: "cat-burgers",
      name: "McNífico Bacon",
      description:
        "Hambúrguer, bacon crocante, queijo, alface, tomate, cebola e maionese",
      price: 32.9,
      active: true,
      featured: true,
      highlight: "promocao",
    },
    {
      id: "p7",
      categoryId: "cat-burgers",
      name: "Chicken Jr.",
      description: "Sanduíche de frango empanado com maionese — tamanho individual",
      price: 12.9,
      active: true,
      featured: true,
      highlight: "promocao",
    },
    {
      id: "p8",
      categoryId: "cat-combos",
      name: "Combo Big Mac",
      description: "Big Mac + batata média + refrigerante 500ml",
      price: 42.9,
      active: true,
      featured: true,
      highlight: "mais_pedidos",
    },
    {
      id: "p9",
      categoryId: "cat-combos",
      name: "Combo McChicken",
      description: "McChicken + batata média + refrigerante 500ml",
      price: 37.9,
      active: true,
    },
    {
      id: "p10",
      categoryId: "cat-sides",
      name: "Batata Frita Média",
      description: "Batatas crocantes com sal",
      price: 14.9,
      active: true,
      extras: [
        { id: "e4", name: "Cheddar", price: 4 },
        { id: "e5", name: "Bacon", price: 4 },
      ],
    },
    {
      id: "p11",
      categoryId: "cat-sides",
      name: "McNuggets 6 unidades",
      description: "Nuggets de frango crocantes com molho à escolha",
      price: 16.9,
      active: true,
    },
    {
      id: "p12",
      categoryId: "cat-drinks",
      name: "Coca-Cola 500ml",
      description: "Refrigerante gelado 500ml",
      price: 9.9,
      active: true,
    },
    {
      id: "p13",
      categoryId: "cat-drinks",
      name: "Milkshake Ovomaltine",
      description: "Milkshake cremoso sabor Ovomaltine — 400ml",
      price: 17.9,
      active: true,
    },
    {
      id: "p14",
      categoryId: "cat-desserts",
      name: "McFlurry Oreo",
      description: "Sorvete de baunilha com pedaços de Oreo e calda",
      price: 14.9,
      active: true,
      featured: true,
      highlight: "promocao",
    },
    {
      id: "p15",
      categoryId: "cat-desserts",
      name: "Sundae Chocolate",
      description: "Sorvete de baunilha com calda de chocolate",
      price: 9.9,
      active: true,
    },
  ],
  coupons: [
    {
      id: "c1",
      code: "BEMVINDO10",
      type: "percent",
      value: 10,
      minOrder: 30,
      active: true,
    },
    {
      id: "c2",
      code: "FRETE0",
      type: "fixed",
      value: 5,
      minOrder: 40,
      active: true,
    },
  ],
  loyalty: [],
  tables: [
    { id: "t1", number: "1", label: "Mesa 1", status: "livre", items: [] },
    { id: "t2", number: "2", label: "Mesa 2", status: "livre", items: [] },
    { id: "t3", number: "3", label: "Mesa 3", status: "livre", items: [] },
    { id: "t4", number: "4", label: "Mesa 4", status: "livre", items: [] },
    { id: "t5", number: "5", label: "Balcão", status: "livre", items: [] },
  ],
  orders: [],
};
